Refactor/migrate api visualizer from vue2 to vue3
Cryolite/mahjongsoul_sniffer pull request #97
Opened 2024-02-28 23:03 UTC by Apricot-S

## 概要

Vue.js 2 が EOL となったため、 Vue.js 3 に移行します
開発ツール・設定も最新のものに変更しています ( 例 : vue/cli → vite )

## 移行対象

API Visualizer のみ
理由 : Game Abstract Crawler と Game Detail Crawler は noVNC でのモニタリングに差し替えて Web UI は廃止するかもしれないとのこと (現在の Web UI にはログ保存機能などがあるため検討中らしい)

## その他

同時に以下の変更も行っています
- `README.md` 中の `docker-compose` を後継の `docker compose` に変更
- `docker-compose.yaml` を後継の `compose.yaml` に変更 バージョン指定も非推奨なので削除
- fix/api_visualizer の変更内容を反映

ライセンスについて、. js 、 .py では GPL/AGPL/LGPL 未使用なのを確認しました

2024-04-24 14:08 UTC, Apricot-S commented
a80e915 にて #98 API Visualizer で ActionPrototype が表示されない に対応しました

2024-05-05 04:49 UTC, Cryolite requested changes
レビューしましたので対応をお願いします．

2024-05-05 04:49 UTC, Cryolite commented on .devcontainer/devcontainer.json
> +	"runArgs": ["--name=mahjongsoul_sniffer-dev"],
コンテナの名前を指定している何か特段の理由や事情はありますか？

2024-05-05 04:49 UTC, Cryolite commented on .devcontainer/post-create.sh
> +
`set -euxo pipefail` を指定するなど，エラー検出を厳格にしたほうが良いのでは？

2024-05-05 04:49 UTC, Cryolite commented on .devcontainer/post-create.sh
> +sudo rm -rf /var/lib/apt/lists/*
システムに Python が依存しているという関係なので， Python パッケージのインストール・アップデートとシステムのアップデートの順序は逆（システムのアップデートのほうが先）のほうが良いのでは？

2024-05-05 04:49 UTC, Cryolite commented on .devcontainer/post-create.sh
> +PROTOC_VERSION=$(curl -s "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
JSON をきちんとパースして値を取り出すツール（ `jq` など）を使ったほうが厳密には良いと思われます．

2024-05-05 04:49 UTC, Cryolite commented on .devcontainer/post-create.sh
> +rm -rf protoc.zip
`-r` は不要．

2024-05-05 04:49 UTC, Cryolite commented on .dockerignore
> +**/.gitignore
`.gitignore` ではなく `**/.gitignore` にしている（ルートディレクトリ以外の `.gitignore` も含める）理由はありますか？

2024-05-05 04:49 UTC, Cryolite commented on .gitignore
> +.mypy_cache/
`/.mypy_cache/` ではなく `.mypy_cache/` にしている（ルートディレクトリ以外の `.mypy_cache` も対象にしている）理由はありますか？

2024-05-05 04:49 UTC, Cryolite commented on .gitignore
> +.ruff_cache/
/.ruff_cache/ ではなく .ruff_cache/ にしている（ルートディレクトリ以外の .mypy_cache も対象にしている）理由はありますか？

2024-05-05 04:49 UTC, Cryolite commented on api-visualizer/build.Dockerfile
> +      ca-certificates \
`Dockerfile` における `apt-get install` のパッケージの順番はアルファベット順でお願いします．

2024-05-05 05:54 UTC, Apricot-S commented on .devcontainer/devcontainer.json
> +	"runArgs": ["--name=mahjongsoul_sniffer-dev"],
ランダムに付与されるよりは識別しやすい名前で固定した方がよいと思い設定しました。

2024-05-05 06:31 UTC, Apricot-S commented on .devcontainer/post-create.sh
> +
40790fda0b1046561af9f0f9f8146d1c1e1343f4 にて追加しました

2024-05-05 06:44 UTC, Apricot-S commented on .devcontainer/post-create.sh
> +sudo rm -rf /var/lib/apt/lists/*
40104b506ad6a04467b2a0746359f0ee425d8b21 にて修正しました。

2024-05-05 06:50 UTC, Apricot-S commented on .devcontainer/post-create.sh
> +rm -rf protoc.zip
343cfc343d474c860139bf49f00e906f9c882648 にて修正しました。

2024-05-05 06:59 UTC, Apricot-S commented on .dockerignore
> +**/.gitignore
/api-visualizer/web-server/vue/.gitignore
/mahjongsoul_sniffer/.gitignore
など、ルートディレクトリ以外にも `.gitignore` が存在するため、それらも除外するために設定しました。
余分なファイルをコピーしない方がよいと考えました。

2024-05-05 07:05 UTC, Apricot-S commented on .gitignore
> +.mypy_cache/
指定ミスです。 fae4fe767532dcc9576b276298190e6fcafd9a89 にて修正しました。

2024-05-05 07:05 UTC, Apricot-S commented on .gitignore
> +.ruff_cache/
指定ミスです。 fae4fe767532dcc9576b276298190e6fcafd9a89 にて修正しました。

2024-05-05 07:12 UTC, Apricot-S commented on api-visualizer/build.Dockerfile
> +      ca-certificates \
3698e2ec5fb8196a8f62a6cdc6c198b57285c8eb にて修正しました。

2024-05-05 07:56 UTC, Apricot-S commented on .devcontainer/post-create.sh
> +PROTOC_VERSION=$(curl -s "https://api.github.com/repos/protocolbuffers/protobuf/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
c50571d1e1cf3981e2ecc368ad320e3e489ac335 にて `jq` を使うように修正しました。

2024-05-05 08:02 UTC, Apricot-S commented
指摘事項に対応しました。

2024-05-05 08:44 UTC, Cryolite commented on .devcontainer/devcontainer.json
> +	"runArgs": ["--name=mahjongsoul_sniffer-dev"],
了解です．

2024-05-05 08:48 UTC, Cryolite approved these changes
LGTM

2024-05-05 08:48 UTC, merged